using CortaFeStudio.Api.Models;
using CortaFeStudio.Api.Services;

namespace CortaFeStudio.Tests;

public sealed class SubtitleTrackTests
{
    [Fact]
    public void Create_GeraBlocosRelativosAPartirDasPalavras()
    {
        var clip = new ClipCandidate { Start = 10, End = 20 };
        var track = SubtitleTrackService.Create(clip,
        [
            new TranscriptSegment
            {
                Start = 11, End = 13, Text = "Tu permaneces fiel",
                Words =
                [
                    new TranscriptWord { Start = 11, End = 11.5, Word = "Tu" },
                    new TranscriptWord { Start = 11.5, End = 12.2, Word = "permaneces" },
                    new TranscriptWord { Start = 12.2, End = 13, Word = "fiel" }
                ]
            }
        ]);

        var block = Assert.Single(track.Blocks);
        Assert.Equal(1, block.Start);
        Assert.InRange(block.End, 3, 3.1);
        Assert.Equal("Tu permaneces fiel", block.Text);
    }

    [Fact]
    public void Validate_PreservaTextoEditadoEDesativacao()
    {
        var track = new SubtitleTrack
        {
            Enabled = false,
            Blocks = [new SubtitleBlock { Start = .4, End = 2.1, Text = "Tu permaneces fiel" }]
        };

        var result = SubtitleTrackService.Validate(track, 10);

        Assert.False(result.Enabled);
        Assert.True(result.EditedByUser);
        Assert.False(result.AutoGenerated);
        Assert.Equal("Tu permaneces fiel", result.Blocks[0].Text);
    }

    [Fact]
    public void Validate_ReparaSobreposicaoSemApagarTexto()
    {
        var track = new SubtitleTrack
        {
            Blocks =
            [
                new SubtitleBlock { Start = 0, End = 2, Text = "Primeiro" },
                new SubtitleBlock { Start = 1.9, End = 3, Text = "Segundo" }
            ]
        };
        var result = SubtitleTrackService.Validate(track, 5);
        Assert.Equal(2, result.Blocks.Count);
        Assert.Equal(result.Blocks[0].End, result.Blocks[1].Start);
        Assert.Equal("Segundo", result.Blocks[1].Text);
    }

    [Fact]
    public void Validate_ReparaBlocoLegadoComDuracaoZero()
    {
        var track = new SubtitleTrack { Blocks = [new SubtitleBlock { Start = 4.36, End = 4.36, Text = "vida para te" }] };
        var result = SubtitleTrackService.Validate(track, 10);
        var block = Assert.Single(result.Blocks);
        Assert.Equal(4.36, block.Start);
        Assert.Equal(4.61, block.End);
        Assert.Equal("vida para te", block.Text);
    }

    [Fact]
    public void BuildAss_UsaTextoEstruturadoEditado()
    {
        var clip = new ClipCandidate
        {
            Start = 10, End = 20,
            SubtitleTrack = new SubtitleTrack
            {
                EditedByUser = true,
                Blocks = [new SubtitleBlock { Start = .4, End = 2.1, Text = "Você está aqui" }]
            }
        };
        var ass = MediaPipeline.BuildAss([], clip);
        Assert.Contains("Você está aqui", ass);
        Assert.Contains("0:00:00.40", ass);
    }

    [Fact]
    public void ComposeVideoFilter_NaoUsaFiltroAssQuandoDesativado()
    {
        var filter = MediaPipeline.ComposeVideoFilter("eq=contrast=1", "scale=1080:1920", null);
        Assert.DoesNotContain("subtitles", filter);
        Assert.Equal("eq=contrast=1,scale=1080:1920", filter);
    }

    [Fact]
    public void Louvor_AplicaPequenaAntecipacaoInicial()
    {
        var clip = new ClipCandidate { Start = 10, End = 20, EditorialProfile = "louvor" };
        var track = SubtitleTrackService.Create(clip,
        [
            new TranscriptSegment { Start = 11, End = 13, Text = "Tu és fiel" }
        ]);
        Assert.Equal(-.18, track.OffsetSeconds);
    }

    [Theory]
    [InlineData(-.4, 0.6, 1.6)]
    [InlineData(.25, 1.25, 2.25)]
    public void EffectiveTiming_AplicaAjusteGeralNoAss(double offset, double expectedStart, double expectedEnd)
    {
        var timing = SubtitleTrackService.EffectiveTiming(
            new SubtitleBlock { Start = 1, End = 2, Text = "Sincronizada" },
            new SubtitleTrack { OffsetSeconds = offset },
            10);
        Assert.NotNull(timing);
        Assert.Equal(expectedStart, timing.Value.Start);
        Assert.Equal(expectedEnd, timing.Value.End);
    }

    [Fact]
    public void BuildAss_RefleteAjusteGeralNoVideoFinal()
    {
        var clip = new ClipCandidate
        {
            Start = 0, End = 10,
            SubtitleTrack = new SubtitleTrack
            {
                OffsetSeconds = -.5,
                Blocks = [new SubtitleBlock { Start = 1, End = 2, Text = "Agora no tempo certo" }]
            }
        };
        var ass = MediaPipeline.BuildAss([], clip);
        Assert.Contains("0:00:00.50", ass);
        Assert.Contains("0:00:01.50", ass);
    }
}
