using CortaFeStudio.Api.Models;
using CortaFeStudio.Api.Services;

namespace CortaFeStudio.Tests;

public sealed class SubtitleLayoutRegressionTests
{
    [Fact]
    public void SemanticUnits_MantemBlocosCurtos()
    {
        var words = Enumerable.Range(0, 12).Select(index => new TranscriptWord
        {
            Start = index * .3,
            End = index * .3 + .22,
            Word = $"palavra{index}"
        }).ToList();

        var units = SubtitleFormatter.SemanticUnits(words);

        Assert.NotEmpty(units);
        Assert.All(units, unit => Assert.InRange(unit.Count, 1, 5));
    }

    [Fact]
    public void Ensure_RefazLegendaAutomaticaGiganteSemTimestampsDePalavra()
    {
        var clip = LegacyClip(editedByUser: false);
        var track = SubtitleTrackService.Ensure(clip, Transcript());

        Assert.True(track.Enabled);
        Assert.Equal(72, track.PositionY);
        Assert.True(track.Blocks.Count > 1);
        Assert.All(track.Blocks, block => Assert.InRange(block.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length, 1, 4));
    }

    [Fact]
    public void Ensure_RefazBlocoGiganteMesmoQuandoFaixaAntigaFoiSalvaNoEditor()
    {
        var clip = LegacyClip(editedByUser: true);
        clip.SubtitleTrack!.AutoGenerated = false;

        var track = SubtitleTrackService.Ensure(clip, Transcript());

        Assert.True(track.Enabled);
        Assert.Equal(72, track.PositionY);
        Assert.True(track.EditedByUser);
        Assert.True(track.Blocks.Count > 1);
        Assert.Equal(
            "Deixa eu ler esse livro aqui cara foi uma bênção pra mim assim e muito entender também sobre prazer em Deus",
            string.Join(' ', track.Blocks.Select(block => block.Text)));
        Assert.All(track.Blocks, block => Assert.InRange(block.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length, 1, 4));
    }

    [Fact]
    public void Validate_ImpedeSalvarParagrafoGiganteComoUmUnicoBloco()
    {
        var track = LegacyClip(editedByUser: true).SubtitleTrack!;

        var validated = SubtitleTrackService.Validate(track, 10);

        Assert.Equal(72, validated.PositionY);
        Assert.True(validated.Blocks.Count > 1);
        Assert.All(validated.Blocks, block => Assert.InRange(block.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length, 1, 4));
    }

    [Fact]
    public void Style_ReduzFonteSemQuebrarMargensSegurasExistentes()
    {
        var clip = new ClipCandidate { SubtitleStyle = "sermon" };
        var style = SubtitleFormatter.Style(clip, 1080, 1920);

        Assert.Contains(",40,", style);
        Assert.EndsWith(",135,135,235,1", style);
    }

    private static ClipCandidate LegacyClip(bool editedByUser) => new()
    {
        Start = 10,
        End = 20,
        SubtitleTrack = new SubtitleTrack
        {
            Enabled = true,
            AutoGenerated = !editedByUser,
            EditedByUser = editedByUser,
            PositionY = 80,
            Blocks =
            [
                new SubtitleBlock
                {
                    Start = 0,
                    End = 10,
                    Text = "Deixa eu ler esse livro aqui cara foi uma bênção pra mim assim e muito entender também sobre prazer em Deus"
                }
            ]
        }
    };

    private static List<TranscriptSegment> Transcript() =>
    [
        new()
        {
            Start = 10,
            End = 20,
            Text = "Deixa eu ler esse livro aqui cara foi uma bênção pra mim assim e muito entender também sobre prazer em Deus"
        }
    ];
}
