using CortaFeStudio.Api.Models;
using CortaFeStudio.Api.Services;

namespace CortaFeStudio.Tests;

public sealed class SubtitleTrackTests
{
    [Fact]
    public void Create_GeraBlocosRelativosAPartirDasPalavras()
    {
        var clip = new ClipCandidate { Start = 10, End = 20 };
        var track = SubtitleTrackService.Create(clip,
        [
            new TranscriptSegment
            {
                Start = 11, End = 13, Text = "Tu permaneces fiel",
                Words =
                [
                    new TranscriptWord { Start = 11, End = 11.5, Word = "Tu" },
                    new TranscriptWord { Start = 11.5, End = 12.2, Word = "permaneces" },
                    new TranscriptWord { Start = 12.2, End = 13, Word = "fiel" }
                ]
            }
        ]);

        var block = Assert.Single(track.Blocks);
        Assert.Equal(1, block.Start);
        Assert.InRange(block.End, 3, 3.1);
        Assert.Equal("Tu permaneces fiel", block.Text);
    }

    [Fact]
    public void Validate_PreservaTextoEditadoEDesativacao()
    {
        var track = new SubtitleTrack
        {
            Enabled = false,
            Blocks = [new SubtitleBlock { Start = .4, End = 2.1, Text = "Tu permaneces fiel" }]
        };

        var result = SubtitleTrackService.Validate(track, 10);

        Assert.False(result.Enabled);
        Assert.True(result.EditedByUser);
        Assert.False(result.AutoGenerated);
        Assert.Equal("Tu permaneces fiel", result.Blocks[0].Text);
    }

    [Fact]
    public void Validate_RejeitaSobreposicao()
    {
        var track = new SubtitleTrack
        {
            Blocks =
            [
                new SubtitleBlock { Start = 0, End = 2, Text = "Primeiro" },
                new SubtitleBlock { Start = 1.9, End = 3, Text = "Segundo" }
            ]
        };
        Assert.Throws<ArgumentException>(() => SubtitleTrackService.Validate(track, 5));
    }

    [Fact]
    public void BuildAss_UsaTextoEstruturadoEditado()
    {
        var clip = new ClipCandidate
        {
            Start = 10, End = 20,
            SubtitleTrack = new SubtitleTrack
            {
                EditedByUser = true,
                Blocks = [new SubtitleBlock { Start = .4, End = 2.1, Text = "Você está aqui" }]
            }
        };
        var ass = MediaPipeline.BuildAss([], clip);
        Assert.Contains("Você está aqui", ass);
        Assert.Contains("0:00:00.40", ass);
    }

    [Fact]
    public void ComposeVideoFilter_NaoUsaFiltroAssQuandoDesativado()
    {
        var filter = MediaPipeline.ComposeVideoFilter("eq=contrast=1", "scale=1080:1920", null);
        Assert.DoesNotContain("subtitles", filter);
        Assert.Equal("eq=contrast=1,scale=1080:1920", filter);
    }
}
