using CortaFeStudio.Api.Models;
using CortaFeStudio.Api.Services;

namespace CortaFeStudio.Tests;

public sealed class SubtitleLayoutRegressionTests
{
    [Fact]
    public void SemanticUnits_LimitaBlocosAutomaticosAQuatroPalavras()
    {
        var words = Enumerable.Range(0, 12).Select(index => new TranscriptWord
        {
            Start = index * .3,
            End = index * .3 + .22,
            Word = $"palavra{index}"
        }).ToList();

        var units = SubtitleFormatter.SemanticUnits(words);

        Assert.NotEmpty(units);
        Assert.All(units, unit => Assert.InRange(unit.Count, 1, 4));
    }

    [Fact]
    public void Ensure_RefazLegendaAutomaticaGiganteSemTimestampsDePalavra()
    {
        var clip = new ClipCandidate
        {
            Start = 10,
            End = 20,
            SubtitleTrack = new SubtitleTrack
            {
                Enabled = true,
                AutoGenerated = true,
                EditedByUser = false,
                PositionY = 80,
                Blocks =
                [
                    new SubtitleBlock
                    {
                        Start = 0,
                        End = 10,
                        Text = "Deixa eu ler esse livro aqui cara foi uma bênção pra mim assim e muito entender também sobre prazer em Deus"
                    }
                ]
            }
        };
        var transcript = new List<TranscriptSegment>
        {
            new()
            {
                Start = 10,
                End = 20,
                Text = "Deixa eu ler esse livro aqui cara foi uma bênção pra mim assim e muito entender também sobre prazer em Deus"
            }
        };

        var track = SubtitleTrackService.Ensure(clip, transcript);

        Assert.True(track.Enabled);
        Assert.Equal(72, track.PositionY);
        Assert.True(track.Blocks.Count > 1);
        Assert.All(track.Blocks, block => Assert.InRange(block.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length, 1, 4));
    }

    [Fact]
    public void Style_UsaFonteEMargemSegurasNoVertical()
    {
        var clip = new ClipCandidate { SubtitleStyle = "sermon" };
        var style = SubtitleFormatter.Style(clip, 1080, 1920);

        Assert.Contains(",40,", style);
        Assert.Contains(",165,165,300,", style);
    }
}
