using System.Text.Json;
using CortaFeStudio.Api.Models;

namespace CortaFeStudio.Api.Services;

public sealed class ClipSubtitleTranscriptionService(ToolService tools, ProjectStore store, ProductionWorkLimiter workLimiter)
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web) { PropertyNameCaseInsensitive = true };

    public async Task<SubtitleTrack> TranscribeAsync(VideoProject project, ClipCandidate clip, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(project.LocalMedia))
            throw new InvalidOperationException("O vídeo original não está disponível para transcrever este corte.");

        var directory = store.ProjectDirectory(project.Id);
        var source = Path.Combine(directory, project.LocalMedia);
        if (!File.Exists(source))
            throw new InvalidOperationException("O arquivo original deste projeto não foi encontrado.");

        var token = $"subtitle-{clip.Id}-{Guid.NewGuid():N}";
        var audio = Path.Combine(directory, token + ".wav");
        var transcriptFile = Path.Combine(directory, token + ".json");
        try
        {
            await tools.RunAsync(tools.Find("ffmpeg"),
                ["-y", "-ss", clip.Start.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture), "-i", source,
                 "-t", Math.Max(.1, clip.End - clip.Start).ToString("0.###", System.Globalization.CultureInfo.InvariantCulture),
                 "-vn", "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", audio], directory, ct);

            using (await workLimiter.EnterAsync(ProductionWorkKind.Transcription, ct))
                await tools.RunAsync(tools.Find("python"),
                    [Path.Combine(tools.Root, "scripts", "transcribe.py"), audio, transcriptFile, project.Options.WhisperModel, project.Options.ContentType], directory, ct);

            var relative = JsonSerializer.Deserialize<List<TranscriptSegment>>(await File.ReadAllTextAsync(transcriptFile, ct), JsonOptions) ?? [];
            if (relative.Count == 0 || relative.All(segment => string.IsNullOrWhiteSpace(segment.Text)))
                throw new InvalidOperationException("O áudio deste corte não produziu falas utilizáveis para legenda.");

            var track = SubtitleTrackService.Create(clip, MoveToProjectTimeline(relative, clip.Start));
            track.Enabled = true;
            track.AutoGenerated = true;
            track.EditedByUser = false;
            track.QualityWarning = track.RequiresReview
                ? "Legenda criada pelo áudio deste corte. Revise os blocos destacados antes de renderizar."
                : null;
            return track;
        }
        finally
        {
            TryDelete(audio);
            TryDelete(transcriptFile);
        }
    }

    internal static List<TranscriptSegment> MoveToProjectTimeline(IEnumerable<TranscriptSegment> segments, double clipStart) =>
        segments.Select(segment => new TranscriptSegment
        {
            Start = segment.Start + clipStart,
            End = segment.End + clipStart,
            Text = segment.Text,
            Words = segment.Words.Select(word => new TranscriptWord
            {
                Start = word.Start + clipStart,
                End = word.End + clipStart,
                Word = word.Word,
                Probability = word.Probability
            }).ToList()
        }).ToList();

    private static void TryDelete(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); } catch { }
    }
}
