using CortaFeStudio.Api.Models;

namespace CortaFeStudio.Api.Services;

public static class SubtitleTrackService
{
    private const int MaximumAutomaticWordsPerBlock = 4;

    public static SubtitleTrack Ensure(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        if (clip.SubtitleTrack is not null)
        {
            if (clip.SubtitleTrack.Confidence <= 0)
            {
                var existingWords = RelativeWords(clip, transcript);
                ApplyConfidence(clip.SubtitleTrack, existingWords, clip);
            }

            var reflowed = ReflowOversizedBlocks(clip.SubtitleTrack, clip.End - clip.Start);
            if (reflowed && clip.SubtitleTrack.PositionY >= 78)
                clip.SubtitleTrack.PositionY = 72;
            else if (clip.SubtitleTrack.AutoGenerated && !clip.SubtitleTrack.EditedByUser && clip.SubtitleTrack.PositionY >= 78)
                clip.SubtitleTrack.PositionY = 72;

            return clip.SubtitleTrack;
        }

        clip.SubtitleTrack = Create(clip, transcript);
        return clip.SubtitleTrack;
    }

    public static SubtitleTrack Create(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        var words = RelativeWords(clip, transcript);
        var blocks = SubtitleFormatter.SemanticUnits(words).Select(unit => new SubtitleBlock
        {
            Start = Math.Round(unit[0].Start, 3),
            End = Math.Round(Math.Min(clip.End - clip.Start, unit[^1].End + .05), 3),
            Text = string.Join(' ', unit.Select(word => word.Word)),
            Words = unit.ToList()
        }).ToList();

        if (blocks.Count == 0)
            blocks = BuildFallbackBlocks(clip, transcript);

        var track = new SubtitleTrack
        {
            Enabled = false,
            Style = clip.SubtitleStyle,
            PositionX = 50,
            PositionY = 72,
            OffsetSeconds = clip.EditorialProfile == "louvor" ? -.18 : 0,
            AutoGenerated = true,
            LiteralTranscript = true,
            RecommendedStyle = RecommendedStyle(clip.EditorialProfile),
            Blocks = blocks
        };
        ApplyConfidence(track, words, clip);
        track.Enabled = false;
        track.QualityWarning = "Primeira versão sem legendas. Ative e revise a faixa no editor antes de renderizar novamente.";
        NormalizeTimings(track, clip.End - clip.Start);
        return track;
    }

    public static SubtitleTrack Validate(SubtitleTrack track, double clipDuration)
    {
        if (track is null) throw new ArgumentException("A faixa de legendas é obrigatória.");
        track.Style = string.IsNullOrWhiteSpace(track.Style) ? "impact" : track.Style.Trim();
        if (!double.IsFinite(track.OffsetSeconds) || track.OffsetSeconds is < -10 or > 10)
            throw new ArgumentException("O ajuste geral das legendas deve ficar entre -10 e +10 segundos.");
        track.OffsetSeconds = Math.Round(track.OffsetSeconds, 3);
        track.PositionX = Math.Round(Math.Clamp(double.IsFinite(track.PositionX) && track.PositionX > 0 ? track.PositionX : 50, 5, 95), 2);
        track.PositionY = Math.Round(Math.Clamp(double.IsFinite(track.PositionY) && track.PositionY > 0 ? track.PositionY : 72, 5, 95), 2);
        track.Blocks ??= [];
        var reflowed = ReflowOversizedBlocks(track, clipDuration);
        if (reflowed && track.PositionY >= 78) track.PositionY = 72;
        NormalizeTimings(track, clipDuration);
        foreach (var block in track.Blocks)
        {
            block.Text = block.Text?.Trim() ?? "";
            block.Id = string.IsNullOrWhiteSpace(block.Id) ? Guid.NewGuid().ToString("N")[..10] : block.Id;
        }
        track.AutoGenerated = false;
        track.EditedByUser = true;
        track.RequiresReview = false;
        track.QualityWarning = null;
        return track;
    }

    public static bool ReflowOversizedBlocks(SubtitleTrack track, double clipDuration)
    {
        track.Blocks ??= [];
        var changed = false;
        var reflowed = new List<SubtitleBlock>();

        foreach (var block in track.Blocks.OrderBy(block => block.Start))
        {
            var tokens = (block.Text ?? "")
                .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (tokens.Length <= MaximumAutomaticWordsPerBlock)
            {
                reflowed.Add(block);
                continue;
            }

            changed = true;
            var blockStart = Math.Clamp(block.Start, 0, clipDuration);
            var blockEnd = Math.Clamp(Math.Max(block.End, blockStart + .2), 0, clipDuration);
            var blockDuration = Math.Max(.2, blockEnd - blockStart);
            var tokenOffset = 0;
            var groups = tokens.Chunk(MaximumAutomaticWordsPerBlock).ToList();

            for (var index = 0; index < groups.Count; index++)
            {
                var group = groups[index];
                var startRatio = tokenOffset / (double)tokens.Length;
                tokenOffset += group.Length;
                var endRatio = tokenOffset / (double)tokens.Length;
                var start = Math.Clamp(blockStart + blockDuration * startRatio, 0, clipDuration);
                var end = Math.Clamp(blockStart + blockDuration * endRatio, 0, clipDuration);
                if (end - start < .12) end = Math.Min(clipDuration, start + .12);
                if (end <= start) continue;

                reflowed.Add(new SubtitleBlock
                {
                    Id = index == 0 && !string.IsNullOrWhiteSpace(block.Id) ? block.Id : Guid.NewGuid().ToString("N")[..10],
                    Start = Math.Round(start, 3),
                    End = Math.Round(end, 3),
                    Text = string.Join(' ', group),
                    Enabled = block.Enabled,
                    Words = []
                });
            }
        }

        if (!changed) return false;
        track.Blocks = reflowed;
        NormalizeTimings(track, clipDuration);
        return true;
    }

    public static void NormalizeTimings(SubtitleTrack track, double clipDuration)
    {
        var normalized = new List<SubtitleBlock>();
        var previousEnd = 0d;
        foreach (var block in (track.Blocks ?? []).Where(block => double.IsFinite(block.Start) && double.IsFinite(block.End)).OrderBy(block => block.Start))
        {
            var start = Math.Max(Math.Clamp(block.Start, 0, clipDuration), previousEnd);
            var end = Math.Clamp(block.End, 0, clipDuration);
            if (end <= start) end = Math.Min(clipDuration, start + .25);
            if (end - start < .05) continue;
            block.Start = Math.Round(start, 3);
            block.End = Math.Round(end, 3);
            normalized.Add(block);
            previousEnd = block.End;
        }
        track.Blocks = normalized;
    }

    public static (double Start, double End)? EffectiveTiming(SubtitleBlock block, SubtitleTrack track, double clipDuration)
    {
        var start = Math.Clamp(block.Start + track.OffsetSeconds, 0, clipDuration);
        var end = Math.Clamp(block.End + track.OffsetSeconds, 0, clipDuration);
        return end - start < .01 ? null : (Math.Round(start, 3), Math.Round(end, 3));
    }

    private static List<SubtitleBlock> BuildFallbackBlocks(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        var duration = Math.Max(.1, clip.End - clip.Start);
        var blocks = new List<SubtitleBlock>();
        foreach (var segment in transcript.Where(segment => segment.End > clip.Start && segment.Start < clip.End))
        {
            var tokens = segment.Text.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (tokens.Length == 0) continue;

            var segmentStart = Math.Max(clip.Start, segment.Start);
            var segmentEnd = Math.Min(clip.End, Math.Max(segment.End, segmentStart + .2));
            var segmentDuration = Math.Max(.2, segmentEnd - segmentStart);
            var groups = tokens.Chunk(MaximumAutomaticWordsPerBlock).ToList();
            var totalTokens = Math.Max(1, tokens.Length);
            var tokenOffset = 0;

            foreach (var group in groups)
            {
                var startRatio = tokenOffset / (double)totalTokens;
                tokenOffset += group.Length;
                var endRatio = tokenOffset / (double)totalTokens;
                var relativeStart = Math.Clamp(segmentStart - clip.Start + segmentDuration * startRatio, 0, duration);
                var relativeEnd = Math.Clamp(segmentStart - clip.Start + segmentDuration * endRatio, 0, duration);
                if (relativeEnd - relativeStart < .12) relativeEnd = Math.Min(duration, relativeStart + .12);
                if (relativeEnd <= relativeStart) continue;

                blocks.Add(new SubtitleBlock
                {
                    Start = Math.Round(relativeStart, 3),
                    End = Math.Round(relativeEnd, 3),
                    Text = string.Join(' ', group),
                    Words = []
                });
            }
        }
        return blocks;
    }

    private static void ApplyConfidence(SubtitleTrack track, IReadOnlyList<TranscriptWord> words, ClipCandidate clip)
    {
        var duration = Math.Max(.1, clip.End - clip.Start);
        var valid = words.Where((word, index) => double.IsFinite(word.Start) && double.IsFinite(word.End) && word.End > word.Start && (index == 0 || word.Start >= words[index - 1].Start)).ToList();
        var integrity = words.Count == 0 ? 0 : valid.Count / (double)words.Count;
        var density = Math.Clamp(words.Count / duration / 1.6, 0, 1);
        var probabilities = valid.Where(word => word.Probability.HasValue).Select(word => word.Probability!.Value).ToList();
        var acoustic = probabilities.Count >= Math.Max(3, valid.Count / 2) ? probabilities.Average() : .82;
        var hasWordTiming = words.Count >= Math.Max(8, duration / 4) && integrity >= .95;
        track.TimingIntegrity = Math.Round(integrity, 2);
        track.Confidence = hasWordTiming ? Math.Round(Math.Clamp(acoustic * .72 + integrity * .2 + density * .08, 0, .99), 2) : clip.EditorialProfile == "louvor" ? .3 : .55;
        track.ConfidenceLabel = track.Confidence >= .8 ? "alta" : track.Confidence >= .6 ? "média" : "baixa";
        track.RequiresReview = track.Confidence < .9 || clip.EditorialProfile == "louvor";
        if (track.Confidence < .6)
        {
            track.Enabled = false;
            track.QualityWarning = "Sincronização automática sem precisão suficiente. A legenda foi desligada para não publicar texto fora da fala.";
        }
    }

    private static string RecommendedStyle(string profile) => profile switch { "louvor" => "worship", "podcast" => "clean", "pregacao" => "sermon", _ => "impact" };

    private static List<TranscriptWord> RelativeWords(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript) =>
        transcript.SelectMany(segment => segment.Words)
            .Where(word => word.End > clip.Start && word.Start < clip.End)
            .OrderBy(word => word.Start)
            .Select(word => new TranscriptWord
            {
                Start = Math.Max(0, word.Start - clip.Start),
                End = Math.Min(clip.End - clip.Start, word.End - clip.Start),
                Word = word.Word,
                Probability = word.Probability
            }).ToList();
}
