using CortaFeStudio.Api.Models;

namespace CortaFeStudio.Api.Services;

public static class SubtitleTrackService
{
    public static SubtitleTrack Ensure(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        if (clip.SubtitleTrack is not null) return clip.SubtitleTrack;
        clip.SubtitleTrack = Create(clip, transcript);
        return clip.SubtitleTrack;
    }

    public static SubtitleTrack Create(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        var words = transcript.SelectMany(segment => segment.Words)
            .Where(word => word.End > clip.Start && word.Start < clip.End)
            .OrderBy(word => word.Start)
            .Select(word => new TranscriptWord
            {
                Start = Math.Max(0, word.Start - clip.Start),
                End = Math.Min(clip.End - clip.Start, word.End - clip.Start),
                Word = word.Word
            }).ToList();
        if (!string.IsNullOrWhiteSpace(clip.EditedTranscript) && words.Count > 0)
            words = Retext(words, clip.EditedTranscript);

        var blocks = SubtitleFormatter.SemanticUnits(words).Select(unit => new SubtitleBlock
        {
            Start = Math.Round(unit[0].Start, 3),
            End = Math.Round(Math.Min(clip.End - clip.Start, unit[^1].End + .08), 3),
            Text = string.Join(' ', unit.Select(word => word.Word)),
            Words = unit.ToList()
        }).ToList();
        if (blocks.Count == 0)
            blocks = transcript.Where(segment => segment.End > clip.Start && segment.Start < clip.End).Select(segment => new SubtitleBlock
            {
                Start = Math.Round(Math.Max(0, segment.Start - clip.Start), 3),
                End = Math.Round(Math.Min(clip.End - clip.Start, segment.End - clip.Start), 3),
                Text = segment.Text
            }).Where(block => block.End > block.Start && !string.IsNullOrWhiteSpace(block.Text)).ToList();
        return new SubtitleTrack { Enabled = true, Style = clip.SubtitleStyle, AutoGenerated = true, Blocks = blocks };
    }

    public static SubtitleTrack Validate(SubtitleTrack track, double clipDuration)
    {
        if (track is null) throw new ArgumentException("A faixa de legendas é obrigatória.");
        track.Style = string.IsNullOrWhiteSpace(track.Style) ? "impact" : track.Style.Trim();
        track.Blocks ??= [];
        var previousEnd = 0d;
        foreach (var block in track.Blocks.OrderBy(block => block.Start))
        {
            if (!double.IsFinite(block.Start) || !double.IsFinite(block.End) || block.Start < 0 || block.End <= block.Start || block.End > clipDuration + .01)
                throw new ArgumentException("Existe um bloco de legenda com tempo inválido.");
            if (block.Start < previousEnd - .001)
                throw new ArgumentException("Blocos de legenda não podem se sobrepor.");
            block.Text = block.Text?.Trim() ?? "";
            block.Id = string.IsNullOrWhiteSpace(block.Id) ? Guid.NewGuid().ToString("N")[..10] : block.Id;
            previousEnd = block.End;
        }
        track.Blocks = track.Blocks.OrderBy(block => block.Start).ToList();
        track.AutoGenerated = false;
        track.EditedByUser = true;
        return track;
    }

    private static List<TranscriptWord> Retext(List<TranscriptWord> timings, string text)
    {
        var edited = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return edited.Select((word, index) =>
        {
            var position = edited.Length == 1 ? 0 : index / (double)(edited.Length - 1) * (timings.Count - 1);
            var timing = timings[(int)Math.Round(position)];
            return new TranscriptWord { Start = timing.Start, End = timing.End, Word = word };
        }).ToList();
    }
}
