using CortaFeStudio.Api.Models;

namespace CortaFeStudio.Api.Services;

public static class SubtitleTrackService
{
    public static SubtitleTrack Ensure(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        if (clip.SubtitleTrack is not null)
        {
            if (clip.SubtitleTrack.Confidence <= 0)
            {
                var existingWords = RelativeWords(clip, transcript);
                ApplyConfidence(clip.SubtitleTrack, existingWords, clip);
            }
            return clip.SubtitleTrack;
        }
        clip.SubtitleTrack = Create(clip, transcript);
        return clip.SubtitleTrack;
    }

    public static SubtitleTrack Create(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript)
    {
        var words = RelativeWords(clip, transcript);
        if (!string.IsNullOrWhiteSpace(clip.EditedTranscript) && words.Count > 0)
            words = Retext(words, clip.EditedTranscript);

        var blocks = SubtitleFormatter.SemanticUnits(words).Select(unit => new SubtitleBlock
        {
            Start = Math.Round(unit[0].Start, 3),
            End = Math.Round(Math.Min(clip.End - clip.Start, unit[^1].End + .08), 3),
            Text = string.Join(' ', unit.Select(word => word.Word)),
            Words = unit.ToList()
        }).ToList();
        if (blocks.Count == 0)
            blocks = transcript.Where(segment => segment.End > clip.Start && segment.Start < clip.End).Select(segment => new SubtitleBlock
            {
                Start = Math.Round(Math.Max(0, segment.Start - clip.Start), 3),
                End = Math.Round(Math.Min(clip.End - clip.Start, segment.End - clip.Start), 3),
                Text = segment.Text
            }).Where(block => block.End > block.Start && !string.IsNullOrWhiteSpace(block.Text)).ToList();
        var track = new SubtitleTrack
        {
            Enabled = true,
            Style = clip.SubtitleStyle,
            OffsetSeconds = clip.EditorialProfile == "louvor" ? -.18 : 0,
            AutoGenerated = true,
            Blocks = blocks
        };
        ApplyConfidence(track, words, clip);
        NormalizeTimings(track, clip.End - clip.Start);
        return track;
    }

    public static SubtitleTrack Validate(SubtitleTrack track, double clipDuration)
    {
        if (track is null) throw new ArgumentException("A faixa de legendas é obrigatória.");
        track.Style = string.IsNullOrWhiteSpace(track.Style) ? "impact" : track.Style.Trim();
        if (!double.IsFinite(track.OffsetSeconds) || track.OffsetSeconds is < -10 or > 10)
            throw new ArgumentException("O ajuste geral das legendas deve ficar entre -10 e +10 segundos.");
        track.OffsetSeconds = Math.Round(track.OffsetSeconds, 3);
        track.Blocks ??= [];
        NormalizeTimings(track, clipDuration);
        foreach (var block in track.Blocks)
        {
            block.Text = block.Text?.Trim() ?? "";
            block.Id = string.IsNullOrWhiteSpace(block.Id) ? Guid.NewGuid().ToString("N")[..10] : block.Id;
        }
        track.AutoGenerated = false;
        track.EditedByUser = true;
        return track;
    }

    public static void NormalizeTimings(SubtitleTrack track, double clipDuration)
    {
        var normalized = new List<SubtitleBlock>();
        var previousEnd = 0d;
        foreach (var block in (track.Blocks ?? []).Where(block => double.IsFinite(block.Start) && double.IsFinite(block.End)).OrderBy(block => block.Start))
        {
            var start = Math.Max(Math.Clamp(block.Start, 0, clipDuration), previousEnd);
            var end = Math.Clamp(block.End, 0, clipDuration);
            if (end <= start) end = Math.Min(clipDuration, start + .25);
            if (end - start < .05) continue;
            block.Start = Math.Round(start, 3);
            block.End = Math.Round(end, 3);
            normalized.Add(block);
            previousEnd = block.End;
        }
        track.Blocks = normalized;
    }

    public static (double Start, double End)? EffectiveTiming(SubtitleBlock block, SubtitleTrack track, double clipDuration)
    {
        var start = Math.Clamp(block.Start + track.OffsetSeconds, 0, clipDuration);
        var end = Math.Clamp(block.End + track.OffsetSeconds, 0, clipDuration);
        return end - start < .01 ? null : (Math.Round(start, 3), Math.Round(end, 3));
    }

    private static List<TranscriptWord> Retext(List<TranscriptWord> timings, string text)
    {
        var edited = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return edited.Select((word, index) =>
        {
            var position = edited.Length == 1 ? 0 : index / (double)(edited.Length - 1) * (timings.Count - 1);
            var timing = timings[(int)Math.Round(position)];
            return new TranscriptWord { Start = timing.Start, End = timing.End, Word = word };
        }).ToList();
    }

    private static void ApplyConfidence(SubtitleTrack track, IReadOnlyList<TranscriptWord> words, ClipCandidate clip)
    {
        var duration = Math.Max(.1, clip.End - clip.Start);
        var timedSeconds = words.Sum(word => Math.Max(0, word.End - word.Start));
        var coverage = Math.Clamp(timedSeconds / duration, 0, 1);
        var hasWordTiming = words.Count >= Math.Max(8, duration / 4);
        track.Confidence = hasWordTiming
            ? Math.Round(Math.Clamp(.78 + coverage * .2, .78, .98), 2)
            : clip.EditorialProfile == "louvor" ? .3 : .55;
        track.ConfidenceLabel = track.Confidence >= .8 ? "alta" : track.Confidence >= .6 ? "média" : "baixa";
        if (track.Confidence < .6)
        {
            track.Enabled = false;
            track.QualityWarning = "Sincronização automática sem precisão suficiente. A legenda foi desligada para não publicar texto fora da fala.";
        }
    }

    private static List<TranscriptWord> RelativeWords(ClipCandidate clip, IReadOnlyList<TranscriptSegment> transcript) =>
        transcript.SelectMany(segment => segment.Words)
            .Where(word => word.End > clip.Start && word.Start < clip.End)
            .OrderBy(word => word.Start)
            .Select(word => new TranscriptWord
            {
                Start = Math.Max(0, word.Start - clip.Start),
                End = Math.Min(clip.End - clip.Start, word.End - clip.Start),
                Word = word.Word
            }).ToList();
}
